export {default as Layout} from '../Layout/Layout'
export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Contact } from './Contact/Contact'
export {default as Github} from './Github/Github'
export {default as User} from './User/User'